import Head from "next/head";
import PostTitleCard from "~/components/PostTitleCard";
import { api } from "~/utils/api";

export default function Home() {
  const posts = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Application Excercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#fbf9fd] to-[#b3b7ff]">
        <ul>
          {posts.data?.map((post) => {
            return (
              <li key={post.id}>
                <PostTitleCard
                  id={post.id}
                  title={post.title}
                  createdAt={post.createdAt}
                />
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
}
