import Head from "next/head";
import React from "react";
import NavLink from "next/link";

function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen flex-col">
      <Head>
        <title>Application Excercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 flex w-full flex-col justify-between border-b-2 border-black bg-white text-black md:flex-row md:items-center">
        <h2
          className={`border-b-2 border-black px-9 py-4 text-2xl font-light md:border-none`}
        >
          Blogger.com
        </h2>
        <nav>
          <ul className="flex">
            <li className="grow">
              <NavLink
                className={`flex h-full items-center justify-center border-black bg-pink-400 px-9 py-5 text-center font-sans text-lg font-light md:border-x-2`}
                href="/"
              >
                Feed
              </NavLink>
            </li>
            <li className="grow">
              <NavLink
                href="/create"
                className={`flex h-full items-center justify-center bg-black px-9 py-5 text-center font-sans text-lg font-light text-white`}
              >
                Create new post
              </NavLink>
            </li>
          </ul>
        </nav>
      </header>
      {children}
    </div>
  );
}

export default Layout;
